truvami/decoder

- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port7.go
The new port includes a captured time. This reduces the number of mac addresses included in an uplink by one.
Input (port 7): `66EC04BB00E0286D8AABFCBBEC6C9A74B58FB2726C9A74B58DB1E0286D8A9478CBF0B0140C96BBD2260122180D42AD`
```bash
$ decoder tagsl 5 00e0286d8aabfca8e0286d8a9478c2726c9a74b58dab726cdac8b89dacf0b0140c96bbc8
$ decoder tagsl 7 66ec04bb00e0286d8aabfcbbec6c9a74b58fb2726c9a74b58db1e0286d8a9478cbf0b0140c96bbd2260122180d42ad
```
```json
{
"mac1": "e0286d8aabfc",
"mac2": "e0286d8a9478",
"mac3": "726c9a74b58d",
"mac4": "726cdac8b89d",
"mac5": "f0b0140c96bb",
"mac6": "",
"mac7": "",
"moving": false,
"rssi1": -88,
"rssi2": -62,
"rssi3": -85,
"rssi4": -84,
"rssi5": -56,
"rssi6": 0,
"rssi7": 0
}
```
```json
{
"mac1": "e0286d8aabfc",
"mac2": "ec6c9a74b58f",
"mac3": "726c9a74b58d",
"mac4": …
```
> Introduction of port 7 for tagsl. ⚙️

- pkg/decoder/nomadxs/v1/decoder.go
- pkg/decoder/nomadxs/v1/decoder_test.go
- pkg/decoder/nomadxs/v1/port15.go
- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port15.go
- pkg/decoder/tagxl/v1/decoder.go
- pkg/decoder/tagxl/v1/decoder_test.go
- pkg/decoder/tagxl/v1/port151.go
Renamed all battery voltage related fields to match `battery`.
> Updated `battery` key to be consistent. 🚧

- cmd/http_test.go
- pkg/decoder/decoder.go
- pkg/decoder/helpers/helpers.go
- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
Status bytes can now be enabled or disabled for each port separately. Additionally, you can set the position of the status byte, since the tag S / L has the status byte on different indexes.
```go
// example config
decoder.PayloadConfig{
Fields: []decoder.FieldConfig{
{Name: "Moving", Start: 0, Length: 1},
{Name: "Latitude", Start: 1, Length: 4, Transform: func(v interface{}) interface{} {
return float64(v.(int)) / 1000000
}},
{Name: "Longitude", Start: 5, Length: 4, Transform: func(v interface{}) interface{} {
return float64(v.(int)) / 1000000
}},
{Name: "Altitude", Start: 9, Length: 2, Transform: func(v interface{}) interface{} {
return float64(v.(int)) / 10
}},
{Name: "Timestamp", Start: 11, Length: 4},
{Name: "Battery", Start: 15, Length: 2, Transform: func(v interface{}) interface{} …
```
> Added new `StatusByteIndex` to config. 🚧

- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port8.go
Added new decoder configuration for uplinks using port `8`.
```bash
decoder tagsl 8 012c141e9c455738304543434343460078012c01a8c0
[16:59:32.243] INFO: successfully decoded payload {
"data": {
"accelerometerThreshold": 300,
"accelerometerTriggerHoldTimer": 120,
"advertisingFilter": "4048812220199682886",
"bleCurrentConfigurationUplinkInterval": 43200,
"maxBeacons": 30,
"minRssiValue": -100,
"scanInterval": 300,
"scanMode": 1,
"scanTime": 20
},
"metadata": null
}
```
> Added decoder config for port `8`. 🎉

- cmd/http_test.go
- pkg/decoder/helpers/helpers.go
- pkg/decoder/helpers/helpers_test.go
- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port1.go
- pkg/decoder/tagsl/v1/port10.go
- pkg/decoder/tagsl/v1/port105.go
- pkg/decoder/tagsl/v1/port110.go
- pkg/decoder/tagsl/v1/port150.go
- pkg/decoder/tagsl/v1/port151.go
- pkg/decoder/tagsl/v1/port2.go
- pkg/decoder/tagsl/v1/port5.go
- pkg/decoder/tagsl/v1/port50.go
- pkg/decoder/tagsl/v1/port51.go
- pkg/decoder/tagsl/v1/port7.go
- pkg/decoder/tagsl/v1/port8.go
This PR addresses a bug in processing the `moving` flag, ensuring it is correctly interpreted as a hexadecimal string. Previously, the `moving` flag's value was incorrectly processed because it was not handled as a hex string, leading to potential misinterpretations of its state.
Additionally, this PR modifies how the `moving` attribute is accessed. Rather than being directly available in the payloads, the `moving` attribute is now consistently nested within the `metadata` object as `metadata.moving`. This update standardizes attribute access across all payloads, promoting consistency and simplifying downstream data handling.
- **Hex String Handling**: Ensures the `moving` flag is correctly parsed as a hexadecimal string.
- **Consistent Attribute Access**: Standardizes `moving` under …
> Fixed invalid `moving` flag. 🚧

- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port4.go
I added batch size and buffer size as optional fields to the port 4 payload. 
This leads to the max payload length to be 32 bytes and min payload length 28 bytes. 
Also, I could not resist adding some additional validation.
> fix(tagsl): port 4 now accepts optional size fields

- pkg/decoder/smartlabel/v1/decoder.go
- pkg/decoder/smartlabel/v1/decoder_test.go
- pkg/decoder/tagxl/v1/decoder.go
- pkg/decoder/tagxl/v1/decoder_test.go
- pkg/loracloud/middleware.go
- pkg/loracloud/middleware_test.go
Currently, when the XL or SmartLabel decoder is used, LoraCloud returns a 400 Bad Request response code. This issue occurs due to the absence of essential fields, such as `fCount`. This PR addresses that by introducing the `fCount` field, ensuring its proper inclusion in requests.
- **Added `fCount` field**: This field is now included in requests to prevent the 400 Bad Request error.
- **Validation logic**: A validation step has been added to ensure that invalid requests are prevented. The `fCount` value must be set using the new `WithFCount()` function to guarantee it is properly handled.
- **Decoder interface stability**: The `Decoder` interface remains unchanged to maintain backward compatibility and avoid disrupting existing functionality. The `WithFCount()` function has been …
> Extend loracloud middleware with required fields.

- pkg/decoder/nomadxs/v1/decoder_test.go
your removed the temperature validation test in #45 and I think we should have kept it with updated values rather than ditching it instead.
> revert(decoder): add back temperature validation test

- pkg/common/errors.go
- pkg/common/errors_test.go
- pkg/common/helpers.go
- pkg/decoder/nomadxl/v1/decoder.go
- pkg/decoder/nomadxl/v1/decoder_test.go
- pkg/decoder/nomadxs/v1/decoder.go
- pkg/decoder/nomadxs/v1/decoder_test.go
- pkg/decoder/smartlabel/v1/decoder.go
- pkg/decoder/smartlabel/v1/decoder_test.go
- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagxl/v1/decoder.go
- pkg/decoder/tagxl/v1/decoder_test.go
- pkg/encoder/tagsl/v1/encoder.go
- pkg/encoder/tagsl/v1/encoder_test.go
This pull request introduces a new error handling mechanism and updates existing code to use it. The changes include defining new error variables, adding functions to wrap errors, and updating various parts of the codebase to utilize these new functions and error variables.
Error Handling Enhancements:
* [`pkg/common/errors.go`](diffhunk://#diff-c41a146cfaaaff1dcfbd74bb71c443615b15887e1844b56375fa46a263826d68R1-R44): Added new error variables (`ErrPortNotSupported`, `ErrInvalidPayloadLength`, `ErrPayloadTooShort`, `ErrPayloadTooLong`) and functions `WrapError` and `WrapErrorWithMessage` to wrap errors with additional context.
* [`pkg/common/errors_test.go`](diffhunk://#diff-7ac35e96ed2328cec4b7fe9805e9f2342fc7a517ed8d00ef94a38f031edee53dR1-R63): Added tests for the new `WrapError` and …
> Enhanced error messages in `ValidateLength`

- pkg/decoder/decoder.go
- pkg/decoder/reset.go
- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port198.go
This pull request introduces a new feature to handle reset reasons in the decoder package. It includes the addition of new types, constants, and test cases to support this functionality.
* Added `FeatureResetReason` to the list of features in `pkg/decoder/decoder.go`.
* Introduced `UplinkFeatureResetReason` interface with the `GetResetReason` method in `pkg/decoder/decoder.go`.
* Created `ResetReason` type and associated constants for various reset reasons in `pkg/decoder/reset.go`.
* Implemented `Port198Payload` struct and methods to handle reset reasons for port 198 in `pkg/decoder/tagsl/v1/port198.go`.
* Added test cases for port 198 payloads to verify reset reason handling in `pkg/decoder/tagsl/v1/decoder_test.go`. [[1]](diffhunk://#diff-cf70b97fc73f31aadc5518c7229b214fefcbd96375932f64 …
> Added new `Port198Payload` and `FeatureResetReason`.

- pkg/decoder/smartlabel/v1/port1.go
the smartlabel sends port 1 when it has low battery and since the solar cell may be completely covered, we should allow values starting from 0. this fixes #66
> fix(smartlabel): port 1 photovoltaic voltage may be close to zero

- pkg/decoder/tagxl/v1/decoder.go
- pkg/decoder/tagxl/v1/decoder_test.go
- pkg/decoder/tagxl/v1/port150.go
This pull request introduces support for decoding payloads on port 150 in the `tagxl` package. The changes include adding a new payload type, updating the decoder configuration, and enhancing test coverage for the new functionality.
* **Decoder Configuration Update**:
- Added a case for port 150 in the `getConfig` method of `TagXLv1Decoder`. This includes defining a new `PayloadConfig` with a `Timestamp` field, which is parsed and transformed into a `time.Time` object. (`pkg/decoder/tagxl/v1/decoder.go`, [pkg/decoder/tagxl/v1/decoder.goR57-R66](diffhunk://#diff-64e4770928c9661e17ca5d6af8b9f3563582f29462e5a66a5d6f192d3242a4fbR57-R66))
* **New Payload Type**:
- Introduced a new struct `Port150Payload` in a dedicated file (`port150.go`). This struct includes a `Timestamp` field and …
> Support for Port 150 Payloads

- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port15.go
Since port 15 on the tagsl is kinda a heartbeat and therefore sent quite frequently I think we should also parse the duty cycle flag which is provided in the status byte. This would help the understanding of devices which are limiting their airtime because there would be more data points in the timeline.
> feat(tagsl): port 15 parse duty cycle and make feature available

- pkg/decoder/reset.go
- pkg/decoder/tagsl/v1/decoder_test.go
I think we should not be screaming enum values when printing the decoded payload. 
Not like this.
More like this.
> refactor(tagsl): port 198 is no longer screaming reset reason in print

- pkg/decoder/decoder.go
- pkg/decoder/nomadxl/v1/decoder_test.go
- pkg/decoder/nomadxl/v1/port101.go
- pkg/decoder/nomadxs/v1/decoder_test.go
- pkg/decoder/nomadxs/v1/port15.go
- pkg/decoder/smartlabel/v1/decoder_test.go
- pkg/decoder/smartlabel/v1/port1.go
- pkg/decoder/smartlabel/v1/port11.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port10.go
- pkg/decoder/tagsl/v1/port110.go
- pkg/decoder/tagsl/v1/port15.go
- pkg/decoder/tagsl/v1/port150.go
- pkg/decoder/tagsl/v1/port151.go
- pkg/decoder/tagsl/v1/port50.go
- pkg/decoder/tagsl/v1/port51.go
- pkg/decoder/tagxl/v1/decoder_test.go
- pkg/decoder/tagxl/v1/port151.go
We never made the low battery flag available through features. This pull request rectifies this and exposes an optional low battery bool pointer.
> feat(battery): also provide optional low battery pointer for port 15

- pkg/decoder/smartlabel/v1/port197.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port105.go
- pkg/decoder/tagsl/v1/port150.go
- pkg/decoder/tagsl/v1/port151.go
- pkg/decoder/tagsl/v1/port3.go
- pkg/decoder/tagsl/v1/port5.go
- pkg/decoder/tagsl/v1/port50.go
- pkg/decoder/tagsl/v1/port51.go
- pkg/decoder/tagsl/v1/port7.go
We had those validations on a single port so far. I think we should be consistent and do it all across the codebase.
> refactor(validation): validate all rssi values

- pkg/decoder/tagsl/v1/decoder.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port199.go
This is mostly to silence the message flood in the kafka error queue.
> feat(tagsl): support unknown lr1110 199 port

- pkg/decoder/decoder.go
- pkg/decoder/nomadxl/v1/decoder_test.go
- pkg/decoder/nomadxl/v1/port101.go
- pkg/decoder/tagsl/v1/decoder_test.go
- pkg/decoder/tagsl/v1/port105.go
- pkg/decoder/tagsl/v1/port110.go
- pkg/decoder/tagsl/v1/port150.go
- pkg/decoder/tagsl/v1/port151.go
- pkg/decoder/tagxl/v1/decoder_test.go
We expand feature buffered with the is buffered boolean and make buffer level optional as not all devices have one. 
This will help you for your aws feature branch as you can pull this in after it is merged to main.
> refactor(decoder): expand buffered feature and make level optional

- pkg/solver/loracloud/loracloud.go
- pkg/solver/loracloud/metrics.go
> Added metric for valid Traxmate responses

- .github/workflows/ci.yaml
- .gitignore
- .pre-commit-config.yaml
- .secrets.baseline
- .vscode/tasks.json
- .yamllint
- deployment/deployment.yaml
- pkg/encoder/nomadxs/v1/encoder.go
- pkg/encoder/nomadxs/v1/encoder_test.go
- pkg/encoder/smartlabel/v1/encoder.go
- pkg/encoder/smartlabel/v1/encoder_test.go
- pkg/encoder/tagsl/v1/encoder.go
- pkg/encoder/tagsl/v1/encoder_test.go
- pkg/solver/loracloud/metrics.go
This pull request introduces several improvements to CI/CD workflows, code quality tooling, and minor codebase consistency updates. The main focus is on adding pre-commit hooks, secret detection, YAML linting, and enhancing the GitHub Actions workflow for better code hygiene and security. Additionally, there are minor refactors for import statements and metric label consistency.
**CI/CD and Code Quality Tooling**
* Added a `.pre-commit-config.yaml` file to set up pre-commit hooks for formatting, linting, YAML validation, Go code checks, and secret detection. This helps catch issues before code is committed.
* Introduced a `.vscode/tasks.json` task to automatically install pre-commit hooks when the project folder is opened in VS Code, streamlining developer setup.
* Added a `.yamllint` …
> Add custom .yamllint configuration and update CI workflow

- pkg/decoder/tagxl/v1/decoder.go
- pkg/decoder/tagxl/v1/examples_test.go
- pkg/decoder/tagxl/v1/gnss_v2_test.go
- pkg/solver/loracloud/v2/loracloud.go
This pull request standardizes the GNSS NAV grouping port to always use port 192 in the TagXL v1 decoder, replacing previous logic that used ports 193, 194, or 195. The associated tests have been updated to expect port 192 accordingly.
**Port standardization for GNSS NAV grouping:**
* Updated the `TagXLv1Decoder.Decode` method in `decoder.go` to always set the `Port` field to 192 for GNSS NAV grouping, instead of using the incoming port value.
**Test updates for port changes:**
* Modified tests in `examples_test.go` and `gnss_v2_test.go` to expect port 192 instead of 193, 194, or 195, ensuring alignment with the new decoder logic:
- Updated port checks in `TestTagXL_GNSS_Port194_Timestamped` and `TestTagXL_GNSS_Port195_Timestamped` to expect 192. …
> Update GNSS port handling to always use port 192 in decoder and tests
